Fix registration of file reader service
hpi-swa-teaching/SVGMorph pull request #75
Opened 2022-07-17 13:15 UTC by LinqLover

Adds missing #initialize and #unload methods to register SVGMorph as a service for opening svg files as a morph. Fixes #74.

2022-07-19 19:51 UTC, Greenscreen23 requested changes
I didn't even know we had the functionality for accepting dropped files, this seems to work now, thanks for your contribution :)

I'll also talk to the rest of the team, but I think this is fine to merge when the linter is happy ^^

2022-07-19 19:51 UTC, Greenscreen23 commented on packages/SVG-Morphic.package/SVGMorph.class/class/initialize.st
> +	FileServices registerFileReader: self.
```suggestion
	FileServices registerFileReader: self
```

2022-07-19 19:51 UTC, Greenscreen23 commented on packages/SVG-Morphic.package/SVGMorph.class/class/unload.st
> +	FileServices unregisterFileReader: self.
```suggestion
	FileServices unregisterFileReader: self
```

2022-07-21 13:45 UTC, Greenscreen23 approved these changes

2022-07-21 14:11 UTC, merged

2022-07-21 14:43 UTC, LinqLover commented
Thank you!